### PR TITLE
Added argument 'tile_color' to waffle

### PR DESCRIPTION
**Pull request by nateaff**

### CODE REVIEW

**Comment by nateaff** [comment]
Add an argument 'tile_color' to the main `waffle()` function. This would allow the user to change the panel background and have the tile 'grout' match the background.

**Comment by briennakh** [comment]
Why was this deleted? It looks useful, and I'm trying to make the background black, but the tile grout isn't cooperating.

**Comment by nateaff** [comment]
> Why was this deleted? It looks useful, and I'm trying to make the background black, but the tile grout isn't cooperating.

This PR was meant to address the grout coloring problem. I think I deleted because I was going to check that the argument name I suggested make sense and then I never resubmitted.

`waffle.R` is a single function, so if you want an immediate fix you can hack the `waffle()` signature by adding an argument, like I did [here](https://github.com/nateaff/legolda/blob/master/R/waffle2.R) by adding the `grout_color` argument.

**Comment by briennakh** [comment]
Thanks! 

I ended up using a hacky approach to get the same result, without going into the source code: `x$layers[[1]]$aes_params$colour <- 'black'` where `x` is the waffle object.

**Pull request closed without merging**
