### PR TITLE
Create DESCRIPTION

### PR DESCRIPTION
**Pull request by federicomarini**
Installation fails otherwise. Thanks for the package!

### CODE REVIEW

**Comment by hrbrmstr** [comment]
there already is a DESCRIPTION file

**Comment by hrbrmstr** [comment]
I ended up having to tweak the entire namespace/imports/dependency configuration. It all works now, so I'm closing the PR. Thx for the interim fix.

**Comment by timelyportfolio** [comment]
Hope my changes did not screw everything up.  pipeR should not be necessary unless I just missed it somewhere.  I tried to remove it completely.

**Comment by hrbrmstr** [comment]
s'cool. initial break was me having Author: and Authors@. It's totally in
and passing Travis now :-)

**Comment by federicomarini** [comment]
Hi, my initial "fix" was just to remove the second "empty" item in the Authors@R. Good thing you additionally checked the dependencies!

Anyway, I thought I just edited the DESCRIPTION and GitHub prompted you to *add* the file. Lil puzzled, but hey, now it works.

Again, thanks for the package ;)
Federico

**Pull request closed without merging**
